### ISSUE TITLE
Stop using TemporaryGlobalVarName

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/scscp#22]
Right now, SCSCP uses `TemporaryGlobalVarName` to generate "fresh" global vars, with new unique names.

If at all possible, it would be great if this could be avoided; indeed, I'd like to deprecate `TemporaryGlobalVarName` in GAP if possible, see https://github.com/gap-system/gap/issues/2367.

**Comment by alex-konovalov** [comment]
Seeing no progress with this in ANUPQ, I haven't done anything either. In principle, I don't need a cookie to be created via `TemporaryGlobalVarName`, so will be happy to get rid of it.

**Comment by alex-konovalov** [comment]
`TemporaryGlobalVarName` made obsolete in https://github.com/gap-system/gap/pull/3269/ so it's time to act now.
